INSERT INTO MU_LUGAR(Nombre, Tipo, fk_lugar) VALUES
('Amazonas', 'Estado', NULL),
('Anzoátegui', 'Estado', NULL),
('Apure', 'Estado', NULL),
('Aragua', 'Estado', NULL),
('Barinas', 'Estado', NULL),
('Bolívar', 'Estado', NULL),
('Carabobo', 'Estado', NULL),
('Cojedes', 'Estado', NULL),
('Delta Amacuro', 'Estado', NULL),
('Falcón', 'Estado', NULL),
('Guárico', 'Estado', NULL),
('Lara', 'Estado', NULL),
('Mérida', 'Estado', NULL),
('Miranda', 'Estado', NULL),
('Monagas', 'Estado', NULL),
('Nueva Esparta', 'Estado', NULL),
('Portuguesa', 'Estado', NULL),
('Sucre', 'Estado', NULL),
('Táchira', 'Estado', NULL),
('Trujillo', 'Estado', NULL),
('Vargas', 'Estado', NULL),
('Yaracuy', 'Estado', NULL),
('Zulia', 'Estado', NULL),
('Distrito Capital', 'Estado', NULL);

INSERT INTO MU_LUGAR(Nombre, Tipo, fk_lugar) VALUES
('Alto Orinoco','Municipio',1),
('Atabapo','Municipio',1),
('Atures','Municipio',1),
('Autana','Municipio',1),
('Manapiare','Municipio',1),
('Maroa','Municipio',1),
('Río Negro','Municipio',1),
('Anaco','Municipio',2),
('Aragua','Municipio',2),
('Manuel Ezequiel Bruzual','Municipio',2),
('Diego Bautista Urbaneja','Municipio',2),
('Fernando Peñalver','Municipio',2),
('Francisco Del Carmen Carvajal','Municipio',2),
('General Sir Arthur McGregor','Municipio',2),
('Guanta','Municipio',2),
('Independencia','Municipio',2),
('José Gregorio Monagas','Municipio',2),
('Juan Antonio Sotillo','Municipio',2),
('Juan Manuel Cajigal','Municipio',2),
('Libertad','Municipio',2),
('Francisco de Miranda','Municipio',2),
('Pedro María Freites','Municipio',2),
('Píritu','Municipio',2),
('San José de Guanipa','Municipio',2),
('San Juan de Capistrano','Municipio',2),
('Santa Ana','Municipio',2),
('Simón Bolívar','Municipio',2),
('Simón Rodríguez','Municipio',2),
('Achaguas','Municipio',3),
('Biruaca','Municipio',3),
('Muñóz','Municipio',3),
('Páez','Municipio',3),
('Pedro Camejo','Municipio',3),
('Rómulo Gallegos','Municipio',3),
('San Fernando','Municipio',3),
('Atanasio Girardot','Municipio',4),
('Bolívar','Municipio',4),
('Camatagua','Municipio',4),
('Francisco Linares Alcántara','Municipio',4),
('José Ángel Lamas','Municipio',4),
('José Félix Ribas','Municipio',4),
('José Rafael Revenga','Municipio',4),
('Libertador','Municipio',4),
('Mario Briceño Iragorry','Municipio',4),
('Ocumare de la Costa de Oro','Municipio',4),
('San Casimiro','Municipio',4),
('San Sebastián','Municipio',4),
('Santiago Mariño','Municipio',4),
('Santos Michelena','Municipio',4),
('Sucre','Municipio',4),
('Tovar','Municipio',4),
('Urdaneta','Municipio',4),
('Zamora','Municipio',4),
('Alberto Arvelo Torrealba','Municipio',5),
('Andrés Eloy Blanco','Municipio',5),
('Antonio José de Sucre','Municipio',5),
('Arismendi','Municipio',5),
('Barinas','Municipio',5),
('Bolívar','Municipio',5),
('Cruz Paredes','Municipio',5),
('Ezequiel Zamora','Municipio',5),
('Obispos','Municipio',5),
('Pedraza','Municipio',5),
('Rojas','Municipio',5),
('Sosa','Municipio',5),
('Caroní','Municipio',6),
('Cedeño','Municipio',6),
('El Callao','Municipio',6),
('Gran Sabana','Municipio',6),
('Heres','Municipio',6),
('Piar','Municipio',6),
('Angostura (Raúl Leoni)','Municipio',6),
('Roscio','Municipio',6),
('Sifontes','Municipio',6),
('Sucre','Municipio',6),
('Padre Pedro Chien','Municipio',6),
('Bejuma','Municipio',7),
('Carlos Arvelo','Municipio',7),
('Diego Ibarra','Municipio',7),
('Guacara','Municipio',7),
('Juan José Mora','Municipio',7),
('Libertador','Municipio',7),
('Los Guayos','Municipio',7),
('Miranda','Municipio',7),
('Montalbán','Municipio',7),
('Naguanagua','Municipio',7),
('Puerto Cabello','Municipio',7),
('San Diego','Municipio',7),
('San Joaquín','Municipio',7),
('Valencia','Municipio',7),
('Anzoátegui','Municipio',8),
('Tinaquillo','Municipio',8),
('Girardot','Municipio',8),
('Lima Blanco','Municipio',8),
('Pao de San Juan Bautista','Municipio',8),
('Ricaurte','Municipio',8),
('Rómulo Gallegos','Municipio',8),
('San Carlos','Municipio',8),
('Tinaco','Municipio',8),
('Antonio Díaz','Municipio',9),
('Casacoima','Municipio',9),
('Pedernales','Municipio',9),
('Tucupita','Municipio',9),
('Acosta','Municipio',10),
('Bolívar','Municipio',10),
('Buchivacoa','Municipio',10),
('Cacique Manaure','Municipio',10),
('Carirubana','Municipio',10),
('Colina','Municipio',10),
('Dabajuro','Municipio',10),
('Democracia','Municipio',10),
('Falcón','Municipio',10),
('Federación','Municipio',10),
('Jacura','Municipio',10),
('José Laurencio Silva','Municipio',10),
('Los Taques','Municipio',10),
('Mauroa','Municipio',10),
('Miranda','Municipio',10),
('Monseñor Iturriza','Municipio',10),
('Palmasola','Municipio',10),
('Petit','Municipio',10),
('Píritu','Municipio',10),
('San Francisco','Municipio',10),
('Sucre','Municipio',10),
('Tocópero','Municipio',10),
('Unión','Municipio',10),
('Urumaco','Municipio',10),
('Zamora','Municipio',10),
('Camaguán','Municipio',11),
('Chaguaramas','Municipio',11),
('El Socorro','Municipio',11),
('José Félix Ribas','Municipio',11),
('José Tadeo Monagas','Municipio',11),
('Juan Germán Roscio','Municipio',11),
('Julián Mellado','Municipio',11),
('Las Mercedes','Municipio',11),
('Leonardo Infante','Municipio',11),
('Pedro Zaraza','Municipio',11),
('Ortíz','Municipio',11),
('San Gerónimo de Guayabal','Municipio',11),
('San José de Guaribe','Municipio',11),
('Santa María de Ipire','Municipio',11),
('Sebastián Francisco de Miranda','Municipio',11),
('Andrés Eloy Blanco','Municipio',12),
('Crespo','Municipio',12),
('Iribarren','Municipio',12),
('Jiménez','Municipio',12),
('Morán','Municipio',12),
('Palavecino','Municipio',12),
('Simón Planas','Municipio',12),
('Torres','Municipio',12),
('Urdaneta','Municipio',12),
('Alberto Adriani','Municipio',13),
('Andrés Bello','Municipio',13),
('Antonio Pinto Salinas','Municipio',13),
('Aricagua','Municipio',13),
('Arzobispo Chacón','Municipio',13),
('Campo Elías','Municipio',13),
('Caracciolo Parra Olmedo','Municipio',13),
('Cardenal Quintero','Municipio',13),
('Guaraque','Municipio',13),
('Julio César Salas','Municipio',13),
('Justo Briceño','Municipio',13),
('Libertador','Municipio',13),
('Miranda','Municipio',13),
('Obispo Ramos de Lora','Municipio',13),
('Padre Noguera','Municipio',13),
('Pueblo Llano','Municipio',13),
('Rangel','Municipio',13),
('Rivas Dávila','Municipio',13),
('Santos Marquina','Municipio',13),
('Sucre','Municipio',13),
('Tovar','Municipio',13),
('Tulio Febres Cordero','Municipio',13),
('Zea','Municipio',13),
('Acevedo','Municipio',14),
('Andrés Bello','Municipio',14),
('Baruta','Municipio',14),
('Brión','Municipio',14),
('Buroz','Municipio',14),
('Carrizal','Municipio',14),
('Chacao','Municipio',14),
('Cristóbal Rojas','Municipio',14),
('El Hatillo','Municipio',14),
('Guaicaipuro','Municipio',14),
('Independencia','Municipio',14),
('Lander','Municipio',14),
('Los Salias','Municipio',14),
('Páez','Municipio',14),
('Paz Castillo','Municipio',14),
('Pedro Gual','Municipio',14),
('Plaza','Municipio',14),
('Simón Bolívar','Municipio',14),
('Sucre','Municipio',14),
('Urdaneta','Municipio',14),
('Zamora','Municipio',14),
('Acosta','Municipio',15),
('Aguasay','Municipio',15),
('Bolívar','Municipio',15),
('Caripe','Municipio',15),
('Cedeño','Municipio',15),
('Ezequiel Zamora','Municipio',15),
('Libertador','Municipio',15),
('Maturín','Municipio',15),
('Piar','Municipio',15),
('Punceres','Municipio',15),
('Santa Bárbara','Municipio',15),
('Sotillo','Municipio',15),
('Uracoa','Municipio',15),
('Antolín del Campo','Municipio',16),
('Arismendi','Municipio',16),
('García','Municipio',16),
('Gómez','Municipio',16),
('Maneiro','Municipio',16),
('Marcano','Municipio',16),
('Mariño','Municipio',16),
('Península de Macanao','Municipio',16),
('Tubores','Municipio',16),
('Villalba','Municipio',16),
('Díaz','Municipio',16),
('Agua Blanca','Municipio',17),
('Araure','Municipio',17),
('Esteller','Municipio',17),
('Guanare','Municipio',17),
('Guanarito','Municipio',17),
('Monseñor José Vicente de Unda','Municipio',17),
('Ospino','Municipio',17),
('Páez','Municipio',17),
('Papelón','Municipio',17),
('San Genaro de Boconoíto','Municipio',17),
('San Rafael de Onoto','Municipio',17),
('Santa Rosalía','Municipio',17),
('Sucre','Municipio',17),
('Turén','Municipio',17),
('Andrés Eloy Blanco','Municipio',18),
('Andrés Mata','Municipio',18),
('Arismendi','Municipio',18),
('Benítez','Municipio',18),
('Bermúdez','Municipio',18),
('Bolívar','Municipio',18),
('Cajigal','Municipio',18),
('Cruz Salmerón Acosta','Municipio',18),
('Libertador','Municipio',18),
('Mariño','Municipio',18),
('Mejía','Municipio',18),
('Montes','Municipio',18),
('Ribero','Municipio',18),
('Sucre','Municipio',18),
('Valdéz','Municipio',18),
('Andrés Bello','Municipio',19),
('Antonio Rómulo Costa','Municipio',19),
('Ayacucho','Municipio',19),
('Bolívar','Municipio',19),
('Cárdenas','Municipio',19),
('Córdoba','Municipio',19),
('Fernández Feo','Municipio',19),
('Francisco de Miranda','Municipio',19),
('García de Hevia','Municipio',19),
('Guásimos','Municipio',19),
('Independencia','Municipio',19),
('Jáuregui','Municipio',19),
('José María Vargas','Municipio',19),
('Junín','Municipio',19),
('Libertad','Municipio',19),
('Libertador','Municipio',19),
('Lobatera','Municipio',19),
('Michelena','Municipio',19),
('Panamericano','Municipio',19),
('Pedro María Ureña','Municipio',19),
('Rafael Urdaneta','Municipio',19),
('Samuel Darío Maldonado','Municipio',19),
('San Cristóbal','Municipio',19),
('Seboruco','Municipio',19),
('Simón Rodríguez','Municipio',19),
('Sucre','Municipio',19),
('Torbes','Municipio',19),
('Uribante','Municipio',19),
('San Judas Tadeo','Municipio',19),
('Andrés Bello','Municipio',20),
('Boconó','Municipio',20),
('Bolívar','Municipio',20),
('Candelaria','Municipio',20),
('Carache','Municipio',20),
('Escuque','Municipio',20),
('José Felipe Márquez Cañizalez','Municipio',20),
('Juan Vicente Campos Elías','Municipio',20),
('La Ceiba','Municipio',20),
('Miranda','Municipio',20),
('Monte Carmelo','Municipio',20),
('Motatán','Municipio',20),
('Pampán','Municipio',20),
('Pampanito','Municipio',20),
('Rafael Rangel','Municipio',20),
('San Rafael de Carvajal','Municipio',20),
('Sucre','Municipio',20),
('Trujillo','Municipio',20),
('Urdaneta','Municipio',20),
('Valera','Municipio',20),
('Vargas','Municipio',21),
('Arístides Bastidas','Municipio',22),
('Bolívar','Municipio',22),
('Bruzual','Municipio',22),
('Cocorote','Municipio',22),
('Independencia','Municipio',22),
('José Antonio Páez','Municipio',22),
('La Trinidad','Municipio',22),
('Manuel Monge','Municipio',22),
('Nirgua','Municipio',22),
('Peña','Municipio',22),
('San Felipe','Municipio',22),
('Sucre','Municipio',22),
('Urachiche','Municipio',22),
('José Joaquín Veroes','Municipio',22),
('Almirante Padilla','Municipio', 23),
('Baralt','Municipio', 23),
('Cabimas','Municipio', 23),
('Catatumbo','Municipio', 23),
('Colón','Municipio', 23),
('Francisco Javier Pulgar','Municipio', 23),
('Guajira','Municipio', 23),
('Jesús Enrique Losada','Municipio', 23),
('Jesús María Semprún','Municipio', 23),
('La Cañada de Urdaneta','Municipio', 23),
('Lagunillas','Municipio', 23),
('Machiques de Perijá','Municipio', 23),
('Mara','Municipio', 23),
('Maracaibo','Municipio', 23),
('Miranda','Municipio', 23),
('Rosario de Perijá','Municipio', 23),
('San Francisco','Municipio', 23),
('Santa Rita','Municipio', 23),
('Simón Bolívar','Municipio', 23),
('Sucre','Municipio', 23),
('Valmore Rodríguez','Municipio', 23),
('Libertador', 'Municipio',24);

INSERT INTO MU_LUGAR (Nombre, Tipo, fk_lugar) VALUES
('Huachamacare','Parroquia',25),
('Marawaka ','Parroquia',25),
('Mavaca','Parroquia',25),
('Sierra Parima','Parroquia',25),
('La esmeralda','Parroquia',25),
('Ucata','Parroquia',26),
('Yapacana','Parroquia',26),
('Caname','Parroquia',26),
('Atabapo','Parroquia',26),
('Fernando Girón Tovar','Parroquia',27),
('Luis Alberto Gómez','Parroquia',27),
('Parhueña','Parroquia',27),
('Platanillal Platanillal','Parroquia',27),
('Samariapo','Parroquia',28),
('Sipapo','Parroquia',28),
('Munduapo','Parroquia',28),
('Guayapo','Parroquia',28),
('Alto Ventuari','Parroquia',29),
('Medio Ventuari','Parroquia',29),
('Bajo Ventuari','Parroquia',29),
('Victorino','Parroquia',30),
('Comunidad','Parroquia',30),
('Casiquiare','Parroquia',31),
('Cocuy','Parroquia',31),
('Solano','Parroquia',31),
('Anaco','Parroquia',32),
('San Joaquín','Parroquia',32),
('Cachipo','Parroquia',33),
('Aragua de Barcelona','Parroquia',33),
('Clarines','Parroquia',34),
('Guanape','Parroquia',34),
('Sabana de Uchire','Parroquia',34),
('Lechería','Parroquia',35),
('El Morro','Parroquia',35),
('Puerto Píritu','Parroquia',36),
('San Miguel','Parroquia',36),
('Sucre','Parroquia',36),
('Valle de Guanape','Parroquia',37),
('Santa Bárbara','Parroquia',37),
('El Chaparro','Parroquia',38),
('Tomás Alfaro','Parroquia',38),
('Calatrava','Parroquia',38),
('Guanta','Parroquia',39),
('Chorrerón','Parroquia',39),
('Mamo','Parroquia',40),
('Soledad','Parroquia',40),
('Mapire','Parroquia',41),
('Piar','Parroquia',41),
('Santa Clara','Parroquia',41),
('San Diego de Cabrutica','Parroquia',41),
('Uverito','Parroquia',41),
('Zuata','Parroquia',41),
('Puerto La Cruz','Parroquia',42),
('Pozuelos','Parroquia',42),
('Onoto','Parroquia',43),
('San Pablo','Parroquia',43),
('San Mateo','Parroquia',44),
('El Carito','Parroquia',44),
('Santa Inés','Parroquia',44),
('La Romereña','Parroquia',44),
('Atapirire','Parroquia',45),
('Boca del Pao','Parroquia',45),
('El Pao','Parroquia',45),
('Pariaguán','Parroquia',45),
('Cantaura','Parroquia',46),
('Libertador','Parroquia',46),
('Santa Rosa','Parroquia',46),
('Urica','Parroquia',46),
('Píritu','Parroquia',47),
('San Francisco','Parroquia',47),
('San José de Guanipa','Parroquia',48),
('Boca de Uchire','Parroquia',49),
('Boca de Chávez','Parroquia',49),
('Pueblo Nuevo','Parroquia',50),
('Santa Ana','Parroquia',50),
('Bergantín','Parroquia',51),
('Caigua','Parroquia',51),
('El Carmen','Parroquia',51),
('El Pilar','Parroquia',51),
('Naricual','Parroquia',51),
('San Crsitóbal','Parroquia',51),
('Edmundo Barrios','Parroquia',52),
('Miguel Otero Silva','Parroquia',52),
('Achaguas','Parroquia',53),
('Apurito','Parroquia',53),
('El Yagual','Parroquia',53),
('Guachara','Parroquia',53),
('Mucuritas','Parroquia',53),
('Queseras del medio','Parroquia',53),
('Biruaca','Parroquia',54),
('Bruzual','Parroquia',55),
('Mantecal','Parroquia',55),
('Quintero','Parroquia',55),
('Rincón Hondo','Parroquia',55),
('San Vicente','Parroquia',55),
('Guasdualito','Parroquia',56),
('Aramendi','Parroquia',56),
('El Amparo','Parroquia',56),
('San Camilo','Parroquia',56),
('Urdaneta','Parroquia',56),
('San Juan de Payara','Parroquia',57),
('Codazzi','Parroquia',57),
('Cunaviche','Parroquia',57),
('Elorza','Parroquia',58),
('La Trinidad','Parroquia',58),
('San Fernando','Parroquia',59),
('El Recreo','Parroquia',59),
('Peñalver','Parroquia',59),
('San Rafael de Atamaica','Parroquia',59);

INSERT INTO MU_LUGAR(Tipo, fk_lugar, Nombre) VALUES
('Parroquia', 60, 'Pedro José Ovalles'),
('Parroquia', 60, 'Joaquín Crespo'),
('Parroquia', 60, 'José Casanova Godoy'),
('Parroquia', 60, 'Madre María de San José'),
('Parroquia', 60, 'Andrés Eloy Blanco'),
('Parroquia', 60, 'Los Tacarigua'),
('Parroquia', 60, 'Las Delicias'),
('Parroquia', 60, 'Choroní'),
('Parroquia', 61, 'Bolívar'),
('Parroquia', 62, 'Camatagua'),
('Parroquia', 62, 'Carmen de Cura'),
('Parroquia', 63, 'Santa Rita'),
('Parroquia', 63, 'Francisco de Miranda'),
('Parroquia', 63, 'Moseñor Feliciano González'),
('Parroquia', 64, 'Santa Cruz'),
('Parroquia', 65, 'José Félix Ribas'),
('Parroquia', 65, 'Castor Nieves Ríos'),
('Parroquia', 65, 'Las Guacamayas'),
('Parroquia', 65, 'Pao de Zárate'),
('Parroquia', 65, 'Zuata'),
('Parroquia', 66, 'José Rafael Revenga'),
('Parroquia', 67, 'Palo Negro'),
('Parroquia', 67, 'San Martín de Porres'),
('Parroquia', 68, 'El Limón'),
('Parroquia', 68, 'Caña de Azúcar'),
('Parroquia', 69, 'Ocumare de la Costa'),
('Parroquia', 70, 'San Casimiro'),
('Parroquia', 70, 'Güiripa'),
('Parroquia', 70, 'Ollas de Caramacate'),
('Parroquia', 70, 'Valle Morín'),
('Parroquia', 71, 'San Sebastían'),
('Parroquia', 72, 'Turmero'),
('Parroquia', 72, 'Arevalo Aponte'),
('Parroquia', 72, 'Chuao'),
('Parroquia', 72, 'Samán de Güere'),
('Parroquia', 72, 'Alfredo Pacheco Miranda'),
('Parroquia', 73, 'Santos Michelena'),
('Parroquia', 73, 'Tiara'),
('Parroquia', 74, 'Cagua'),
('Parroquia', 74, 'Bella Vista'),
('Parroquia', 75, 'Tovar'),
('Parroquia', 76, 'Urdaneta'),
('Parroquia', 76, 'Las Peñitas'),
('Parroquia', 76, 'San Francisco de Cara'),
('Parroquia', 76, 'Taguay'),
('Parroquia', 77, 'Zamora'),
('Parroquia', 77, 'Magdaleno'),
('Parroquia', 77, 'San Francisco de Asís'),
('Parroquia', 77, 'Valles de Tucutunemo'),
('Parroquia', 77, 'Augusto Mijares'),
('Parroquia', 78, 'Sabaneta'),
('Parroquia', 78, 'Juan Antonio Rodríguez Domínguez'),
('Parroquia', 79, 'El Cantón'),
('Parroquia', 79, 'Santa Cruz de Guacas'),
('Parroquia', 79, 'Puerto Vivas'),
('Parroquia', 80, 'Ticoporo'),
('Parroquia', 80, 'Nicolás Pulido'),
('Parroquia', 80, 'Andrés Bello'),
('Parroquia', 81, 'Arismendi'),
('Parroquia', 81, 'Guadarrama'),
('Parroquia', 81, 'La Unión'),
('Parroquia', 81, 'San Antonio'),
('Parroquia', 82, 'Barinas'),
('Parroquia', 82, 'Alberto Arvelo Larriva'),
('Parroquia', 82, 'San Silvestre'),
('Parroquia', 82, 'Santa Inés'),
('Parroquia', 82, 'Santa Lucía'),
('Parroquia', 82, 'Torumos'),
('Parroquia', 82, 'El Carmen'),
('Parroquia', 82, 'Rómulo Betancourt'),
('Parroquia', 82, 'Corazón de Jesús'),
('Parroquia', 82, 'Ramón Ignacio Méndez'),
('Parroquia', 82, 'Alto Barinas'),
('Parroquia', 82, 'Manuel Palacio Fajardo'),
('Parroquia', 82, 'Juan Antonio Rodríguez Domínguez'),
('Parroquia', 82, 'Dominga Ortiz de Páez'),
('Parroquia', 83, 'Barinitas'),
('Parroquia', 83, 'Altamira de Cáceres'),
('Parroquia', 83, 'Calderas'),
('Parroquia', 84, 'Barrancas'),
('Parroquia', 84, 'El Socorro'),
('Parroquia', 84, 'Mazparrito'),
('Parroquia', 85, 'Santa Bárbara'),
('Parroquia', 85, 'Pedro Briceño Méndez'),
('Parroquia', 85, 'Ramón Ignacio Méndez'),
('Parroquia', 85, 'José Ignacio del Pumar'),
('Parroquia', 86, 'Obispos'),
('Parroquia', 86, 'Guasimitos'),
('Parroquia', 86, 'El Real'),
('Parroquia', 86, 'La Luz'),
('Parroquia', 87, 'Ciudad Bolívia'),
('Parroquia', 87, 'José Ignacio Briceño'),
('Parroquia', 87, 'José Félix Ribas'),
('Parroquia', 87, 'Páez'),
('Parroquia', 88, 'Libertad'),
('Parroquia', 88, 'Dolores'),
('Parroquia', 88, 'Santa Rosa'),
('Parroquia', 88, 'Palacio Fajardo'),
('Parroquia', 89, 'Ciudad de Nutrias'),
('Parroquia', 89, 'El Regalo'),
('Parroquia', 89, 'Puerto Nutrias'),
('Parroquia', 89, 'Santa Catalina'),
('Parroquia', 90, 'Cachamay'),
('Parroquia', 90, 'Chirica'),
('Parroquia', 90, 'Dalla Costa'),
('Parroquia', 90, 'Once de Abril'),
('Parroquia', 90, 'Simón Bolívar'),
('Parroquia', 90, 'Unare'),
('Parroquia', 90, 'Universidad'),
('Parroquia', 90, 'Vista al Sol'),
('Parroquia', 90, 'Pozo Verde'),
('Parroquia', 90, 'Yocoima'),
('Parroquia', 90, '5 de Julio'),
('Parroquia', 91, 'Cedeño'),
('Parroquia', 91, 'Altagracia'),
('Parroquia', 91, 'Ascensión Farreras'),
('Parroquia', 91, 'Guaniamo'),
('Parroquia', 91, 'La Urbana'),
('Parroquia', 91, 'Pijiguaos'),
('Parroquia', 92, 'El Callao'),
('Parroquia', 93, 'Gran Sabana'),
('Parroquia', 93, 'Ikabarú'),
('Parroquia', 94, 'Catedral'),
('Parroquia', 94, 'Zea'),
('Parroquia', 94, 'Orinoco'),
('Parroquia', 94, 'José Antonio Páez'),
('Parroquia', 94, 'Marhuanta'),
('Parroquia', 94, 'Agua Salada'),
('Parroquia', 94, 'Vista Hermosa'),
('Parroquia', 94, 'La Sabanita'),
('Parroquia', 94, 'Panapana'),
('Parroquia', 95, 'Andrés Eloy Blanco'),
('Parroquia', 95, 'Pedro Cova'),
('Parroquia', 96, 'Raúl Leoni'),
('Parroquia', 96, 'Barceloneta'),
('Parroquia', 96, 'Santa Bárbara'),
('Parroquia', 96, 'San Francisco'),
('Parroquia', 97, 'Roscio'),
('Parroquia', 97, 'Salóm'),
('Parroquia', 98, 'Sifontes'),
('Parroquia', 98, 'Dalla Costa'),
('Parroquia', 98, 'San Isidro'),
('Parroquia', 99, 'Sucre'),
('Parroquia', 99, 'Aripao'),
('Parroquia', 99, 'Guarataro'),
('Parroquia', 99, 'Las Majadas'),
('Parroquia', 99, 'Moitaco'),
('Parroquia', 100, 'Padre Pedro Chien'),
('Parroquia', 100, 'Río Grande'),
('Parroquia', 101, 'Bejuma'),
('Parroquia', 101, 'Canoabo'),
('Parroquia', 101, 'Simón Bolívar'),
('Parroquia', 102, 'Güigüe'),
('Parroquia', 102, 'Carabobo'),
('Parroquia', 102, 'Tacarigua'),
('Parroquia', 103, 'Mariara'),
('Parroquia', 103, 'Aguas Calientes'),
('Parroquia', 104, 'Ciudad Alianza'),
('Parroquia', 104, 'Guacara'),
('Parroquia', 104, 'Yagua'),
('Parroquia', 105, 'Morón'),
('Parroquia', 105, 'Yagua'),
('Parroquia', 106, 'Tocuyito'),
('Parroquia', 106, 'Independencia'),
('Parroquia', 107, 'Los Guayos'),
('Parroquia', 108, 'Miranda'),
('Parroquia', 109, 'Montalbán'),
('Parroquia', 110, 'Naguanagua'),
('Parroquia', 111, 'Bartolomé Salóm'),
('Parroquia', 111, 'Democracia'),
('Parroquia', 111, 'Fraternidad'),
('Parroquia', 111, 'Goaigoaza'),
('Parroquia', 111, 'Juan José Flores'),
('Parroquia', 111, 'Unión'),
('Parroquia', 111, 'Borburata'),
('Parroquia', 111, 'Patanemo'),
('Parroquia', 112, 'San Diego'),
('Parroquia', 113, 'San Joaquín'),
('Parroquia', 114, 'Candelaria'),
('Parroquia', 114, 'Catedral'),
('Parroquia', 114, 'El Socorro'),
('Parroquia', 114, 'Miguel Peña'),
('Parroquia', 114, 'Rafael Urdaneta'),
('Parroquia', 114, 'San Blas'),
('Parroquia', 114, 'San José'),
('Parroquia', 114, 'Santa Rosa'),
('Parroquia', 114, 'Negro Primero'),
('Parroquia', 115, 'Cojedes'),
('Parroquia', 115, 'Juan de Mata Suárez'),
('Parroquia', 116, 'Tinaquillo'),
('Parroquia', 117, 'El Baúl'),
('Parroquia', 117, 'Sucre'),
('Parroquia', 118, 'La Aguadita'),
('Parroquia', 118, 'Macapo'),
('Parroquia', 119, 'El Pao'),
('Parroquia', 120, 'El Amparo'),
('Parroquia', 120, 'Libertad de Cojedes'),
('Parroquia', 121, 'Rómulo Gallegos'),
('Parroquia', 122, 'San Carlos de Austria'),
('Parroquia', 122, 'Juan Ángel Bravo'),
('Parroquia', 122, 'Manuel Manrique'),
('Parroquia', 123, 'General en Jefe José Laurencio Silva'),
('Parroquia', 124, 'Curiapo'),
('Parroquia', 124, 'Almirante Luis Brión'),
('Parroquia', 124, 'Francisco Aniceto Lugo'),
('Parroquia', 124, 'Manuel Renaud'),
('Parroquia', 124, 'Padre Barral'),
('Parroquia', 124, 'Santos de Abelgas'),
('Parroquia', 125, 'Imataca'),
('Parroquia', 125, 'Cinco de Julio'),
('Parroquia', 125, 'Juan Bautista Arismendi'),
('Parroquia', 125, 'Manuel Piar'),
('Parroquia', 125, 'Rómulo Gallegos'),
('Parroquia', 126, 'Pedernales'),
('Parroquia', 126, 'Luis Beltrán Prieto Figueroa'),
('Parroquia', 127, 'San José (Delta Amacuro)'),
('Parroquia', 127, 'José Vidal Marcano'),
('Parroquia', 127, 'Juan Millán'),
('Parroquia', 127, 'Leonardo Ruíz Pineda'),
('Parroquia', 127, 'Mariscal Antonio José de Sucre'),
('Parroquia', 127, 'Monseñor Argimiro García'),
('Parroquia', 127, 'San Rafael (Delta Amacuro)'),
('Parroquia', 127, 'Virgen del Valle'),
('Parroquia', 128, 'Capadare'),
('Parroquia', 128, 'La Pastora'),
('Parroquia', 128, 'Libertador'),
('Parroquia', 128, 'San Juan de los Cayos'),
('Parroquia', 129, 'Aracua'),
('Parroquia', 129, 'La Peña'),
('Parroquia', 129, 'San Luis'),
('Parroquia', 130, 'Bariro'),
('Parroquia', 130, 'Borojó'),
('Parroquia', 130, 'Capatárida'),
('Parroquia', 130, 'Guajiro'),
('Parroquia', 130, 'Seque'),
('Parroquia', 130, 'Zazárida'),
('Parroquia', 130, 'Valle de Eroa'),
('Parroquia', 131, 'Cacique Manaure'),
('Parroquia', 132, 'Norte'),
('Parroquia', 132, 'Carirubana'),
('Parroquia', 132, 'Santa Ana'),
('Parroquia', 132, 'Urbana Punta Cardón'),
('Parroquia', 133, 'La Vela de Coro'),
('Parroquia', 133, 'Acurigua'),
('Parroquia', 133, 'Guaibacoa'),
('Parroquia', 133, 'Las Calderas'),
('Parroquia', 133, 'Macoruca'),
('Parroquia', 134, 'Dabajuro'),
('Parroquia', 135, 'Agua Clara'),
('Parroquia', 135, 'Avaria'),
('Parroquia', 135, 'Pedregal'),
('Parroquia', 135, 'Piedra Grande'),
('Parroquia', 135, 'Purureche'),
('Parroquia', 136, 'Adaure'),
('Parroquia', 136, 'Adícora'),
('Parroquia', 136, 'Baraived'),
('Parroquia', 136, 'Buena Vista'),
('Parroquia', 136, 'Jadacaquiva'),
('Parroquia', 136, 'El Vínculo'),
('Parroquia', 136, 'El Hato'),
('Parroquia', 136, 'Moruy'),
('Parroquia', 136, 'Pueblo Nuevo'),
('Parroquia', 137, 'Agua Larga'),
('Parroquia', 137, 'El Paují'),
('Parroquia', 137, 'Independencia'),
('Parroquia', 137, 'Mapararí'),
('Parroquia', 137, 'Churuguara'),
('Parroquia', 138, 'Agua Linda'),
('Parroquia', 138, 'Araurima'),
('Parroquia', 138, 'Jacura'),
('Parroquia', 139, 'Tucacas'),
('Parroquia', 139, 'Boca de Aroa'),
('Parroquia', 140, 'Los Taques'),
('Parroquia', 140, 'Judibana'),
('Parroquia', 141, 'Mene de Mauroa'),
('Parroquia', 141, 'San Félix'),
('Parroquia', 141, 'Casigua'),
('Parroquia', 142, 'Guzmán Guillermo'),
('Parroquia', 142, 'Mitare'),
('Parroquia', 142, 'Río Seco'),
('Parroquia', 142, 'Sabaneta'),
('Parroquia', 142, 'San Antonio'),
('Parroquia', 142, 'San Gabriel'),
('Parroquia', 142, 'Santa Ana'),
('Parroquia', 143, 'Boca del Tocuyo'),
('Parroquia', 143, 'Chichiriviche'),
('Parroquia', 143, 'Tocuyo de la Costa'),
('Parroquia', 144, 'Palmasola'),
('Parroquia', 145, 'Cabure'),
('Parroquia', 145, 'Colina'),
('Parroquia', 145, 'Curimagua'),
('Parroquia', 146, 'San José de la Costa'),
('Parroquia', 146, 'Píritu'),
('Parroquia', 147, 'San Francisco'),
('Parroquia', 148, 'Sucre'),
('Parroquia', 148, 'Pecaya'),
('Parroquia', 149, 'Tocópero'),
('Parroquia', 150, 'El Charal'),
('Parroquia', 150, 'Las Vegas del Tuy'),
('Parroquia', 150, 'Santa Cruz de Bucaral'),
('Parroquia', 151, 'Bruzual'),
('Parroquia', 151, 'Urumaco'),
('Parroquia', 152, 'Puerto Cumarebo'),
('Parroquia', 152, 'La Ciénaga'),
('Parroquia', 152, 'La Soledad'),
('Parroquia', 152, 'Pueblo Cumarebo'),
('Parroquia', 152, 'Zazárida'),
('Parroquia', 153, 'Camaguán'),
('Parroquia', 153, 'Puerto Miranda'),
('Parroquia', 153, 'Uverito'),
('Parroquia', 154, 'Chaguaramas'),
('Parroquia', 155, 'El Socorro'),
('Parroquia', 156, 'Tucupido'),
('Parroquia', 156, 'San Rafael de Laya'),
('Parroquia', 157, 'Altagracia de Orituco'),
('Parroquia', 157, 'San Rafael de Orituco'),
('Parroquia', 157, 'San Francisco Javier de Lezama'),
('Parroquia', 157, 'Paso Real de Macaira'),
('Parroquia', 157, 'Carlos Soublette'),
('Parroquia', 157, 'San Francisco de Macaira'),
('Parroquia', 157, 'Libertad de Orituco'),
('Parroquia', 158, 'Cantaclaro'),
('Parroquia', 158, 'San Juan de los Morros'),
('Parroquia', 158, 'Parapara'),
('Parroquia', 159, 'El Sombrero'),
('Parroquia', 159, 'Sosa'),
('Parroquia', 160, 'Las Mercedes'),
('Parroquia', 160, 'Cabruta'),
('Parroquia', 160, 'Santa Rita de Manapire'),
('Parroquia', 161, 'Valle de la Pascua'),
('Parroquia', 161, 'Espino'),
('Parroquia', 162, 'San José de Unare'),
('Parroquia', 162, 'Zaraza'),
('Parroquia', 163, 'San José de Tiznados'),
('Parroquia', 163, 'San Francisco de Tiznados'),
('Parroquia', 163, 'San Lorenzo de Tiznados'),
('Parroquia', 163, 'Ortiz'),
('Parroquia', 164, 'Guayabal'),
('Parroquia', 164, 'Cazorla'),
('Parroquia', 165, 'San José de Guaribe'),
('Parroquia', 165, 'Uveral'),
('Parroquia', 166, 'Santa María de Ipire'),
('Parroquia', 166, 'Altamira'),
('Parroquia', 167, 'El Calvario'),
('Parroquia', 167, 'El Rastro'),
('Parroquia', 167, 'Guardatinajas'),
('Parroquia', 167, 'Capital Urbana Calabozo'),
('Parroquia', 168, 'Quebrada Honda de Guache'),
('Parroquia', 168, 'Pío Tamayo'),
('Parroquia', 168, 'Yacambú'),
('Parroquia', 169, 'Fréitez'),
('Parroquia', 169, 'José María Blanco'),
('Parroquia', 170, 'Catedral'),
('Parroquia', 170, 'Concepción'),
('Parroquia', 170, 'El Cují'),
('Parroquia', 170, 'Juan de Villegas'),
('Parroquia', 170, 'Santa Rosa'),
('Parroquia', 170, 'Tamaca'),
('Parroquia', 170, 'Unión'),
('Parroquia', 170, 'Aguedo Felipe Alvarado'),
('Parroquia', 170, 'Buena Vista'),
('Parroquia', 170, 'Juárez'),
('Parroquia', 171, 'Juan Bautista Rodríguez'),
('Parroquia', 171, 'Cuara'),
('Parroquia', 171, 'Diego de Lozada'),
('Parroquia', 171, 'Paraíso de San José'),
('Parroquia', 171, 'San Miguel'),
('Parroquia', 171, 'Tintorero'),
('Parroquia', 171, 'José Bernardo Dorante'),
('Parroquia', 171, 'Coronel Mariano Peraza '),
('Parroquia', 172, 'Bolívar'),
('Parroquia', 172, 'Anzoátegui'),
('Parroquia', 172, 'Guarico'),
('Parroquia', 172, 'Hilario Luna y Luna'),
('Parroquia', 172, 'Humocaro Alto'),
('Parroquia', 172, 'Humocaro Bajo'),
('Parroquia', 172, 'La Candelaria'),
('Parroquia', 172, 'Morán'),
('Parroquia', 173, 'Cabudare'),
('Parroquia', 173, 'José Gregorio Bastidas'),
('Parroquia', 173, 'Agua Viva'),
('Parroquia', 174, 'Sarare'),
('Parroquia', 174, 'Buría'),
('Parroquia', 174, 'Gustavo Vegas León'),
('Parroquia', 175, 'Trinidad Samuel'),
('Parroquia', 175, 'Antonio Díaz'),
('Parroquia', 175, 'Camacaro'),
('Parroquia', 175, 'Castañeda'),
('Parroquia', 175, 'Cecilio Zubillaga'),
('Parroquia', 175, 'Chiquinquirá'),
('Parroquia', 175, 'El Blanco'),
('Parroquia', 175, 'Espinoza de los Monteros'),
('Parroquia', 175, 'Lara'),
('Parroquia', 175, 'Las Mercedes'),
('Parroquia', 175, 'Manuel Morillo'),
('Parroquia', 175, 'Montaña Verde'),
('Parroquia', 175, 'Montes de Oca'),
('Parroquia', 175, 'Torres'),
('Parroquia', 175, 'Heriberto Arroyo'),
('Parroquia', 175, 'Reyes Vargas'),
('Parroquia', 175, 'Altagracia'),
('Parroquia', 176, 'Siquisique'),
('Parroquia', 176, 'Moroturo'),
('Parroquia', 176, 'San Miguel'),
('Parroquia', 176, 'Xaguas'),
('Parroquia', 177, 'Presidente Betancourt'),
('Parroquia', 177, 'Presidente Páez'),
('Parroquia', 177, 'Presidente Rómulo Gallegos'),
('Parroquia', 177, 'Gabriel Picón González'),
('Parroquia', 177, 'Héctor Amable Mora'),
('Parroquia', 177, 'José Nucete Sardi'),
('Parroquia', 177, 'Pulido Méndez'),
('Parroquia', 178, 'La Azulita'),
('Parroquia', 179, 'Santa Cruz de Mora'),
('Parroquia', 179, 'Mesa Bolívar'),
('Parroquia', 179, 'Mesa de Las Palmas'),
('Parroquia', 180, 'Aricagua'),
('Parroquia', 180, 'San Antonio'),
('Parroquia', 181, 'Canagua'),
('Parroquia', 181, 'Capurí'),
('Parroquia', 181, 'Chacantá'),
('Parroquia', 181, 'El Molino'),
('Parroquia', 181, 'Guaimaral'),
('Parroquia', 181, 'Mucutuy'),
('Parroquia', 181, 'Mucuchachí'),
('Parroquia', 182, 'Fernández Peña'),
('Parroquia', 182, 'Matriz'),
('Parroquia', 182, 'Montalbán'),
('Parroquia', 182, 'Acequias'),
('Parroquia', 182, 'Jají'),
('Parroquia', 182, 'La Mesa'),
('Parroquia', 182, 'San José del Sur'),
('Parroquia', 183, 'Tucaní'),
('Parroquia', 183, 'Florencio Ramírez'),
('Parroquia', 184, 'Santo Domingo'),
('Parroquia', 184, 'Las Piedras'),
('Parroquia', 185, 'Guaraque'),
('Parroquia', 185, 'Mesa de Quintero'),
('Parroquia', 185, 'Río Negro'),
('Parroquia', 186, 'Arapuey'),
('Parroquia', 186, 'Palmira'),
('Parroquia', 187, 'San Cristóbal de Torondoy'),
('Parroquia', 187, 'Torondoy'),
('Parroquia', 188, 'Antonio Spinetti Dini'),
('Parroquia', 188, 'Arias'),
('Parroquia', 188, 'Caracciolo Parra Pérez'),
('Parroquia', 188, 'Domingo Peña'),
('Parroquia', 188, 'El Llano'),
('Parroquia', 188, 'Gonzalo Picón Febres'),
('Parroquia', 188, 'Jacinto Plaza'),
('Parroquia', 188, 'Juan Rodríguez Suárez'),
('Parroquia', 188, 'Lasso de la Vega'),
('Parroquia', 188, 'Mariano Picón Salas'),
('Parroquia', 188, 'Milla'),
('Parroquia', 188, 'Osuna Rodríguez'),
('Parroquia', 188, 'Sagrario'),
('Parroquia', 188, 'El Morro'),
('Parroquia', 188, 'Los Nevados'),
('Parroquia', 189, 'Andrés Eloy Blanco'),
('Parroquia', 189, 'La Venta'),
('Parroquia', 189, 'Piñango'),
('Parroquia', 189, 'Timotes'),
('Parroquia', 190, 'Eloy Paredes'),
('Parroquia', 190, 'San Rafael de Alcázar'),
('Parroquia', 190, 'Santa Elena de Arenales'),
('Parroquia', 191, 'Santa María de Caparo'),
('Parroquia', 192, 'Pueblo Llano'),
('Parroquia', 193, 'Cacute'),
('Parroquia', 193, 'La Toma'),
('Parroquia', 193, 'Mucuchíes'),
('Parroquia', 193, 'Mucurubá'),
('Parroquia', 193, 'San Rafael'),
('Parroquia', 194, 'Gerónimo Maldonado'),
('Parroquia', 194, 'Bailadores'),
('Parroquia', 195, 'Tabay'),
('Parroquia', 196, 'Chiguará'),
('Parroquia', 196, 'Estánquez'),
('Parroquia', 196, 'Lagunillas'),
('Parroquia', 196, 'La Trampa'),
('Parroquia', 196, 'Pueblo Nuevo del Sur'),
('Parroquia', 196, 'San Juan'),
('Parroquia', 197, 'El Amparo'),
('Parroquia', 197, 'El Llano'),
('Parroquia', 197, 'San Francisco'),
('Parroquia', 197, 'Tovar'),
('Parroquia', 198, 'Independencia'),
('Parroquia', 198, 'María de la Concepción Palacios Blanco'),
('Parroquia', 198, 'Nueva Bolivia'),
('Parroquia', 198, 'Santa Apolonia'),
('Parroquia', 199, 'Caño El Tigre'),
('Parroquia', 199, 'Zea'),
('Parroquia', 200, 'Aragüita'),
('Parroquia', 200, 'Arévalo González'),
('Parroquia', 200, 'Capaya'),
('Parroquia', 200, 'Caucagua'),
('Parroquia', 200, 'Panaquire'),
('Parroquia', 200, 'Ribas'),
('Parroquia', 200, 'El Café'),
('Parroquia', 200, 'Marizapa'),
('Parroquia', 201, 'Cumbo'),
('Parroquia', 201, 'San José de Barlovento'),
('Parroquia', 202, 'El Cafetal'),
('Parroquia', 202, 'Las Minas'),
('Parroquia', 202, 'Nuestra Señora del Rosario'),
('Parroquia', 203, 'Higuerote'),
('Parroquia', 203, 'Curiepe'),
('Parroquia', 203, 'Tacarigua de Brión'),
('Parroquia', 204, 'Mamporal'),
('Parroquia', 205, 'Carrizal'),
('Parroquia', 206, 'Chacao'),
('Parroquia', 207, 'Charallave'),
('Parroquia', 207, 'Las Brisas'),
('Parroquia', 208, 'El Hatillo'),
('Parroquia', 209, 'Altagracia de la Montaña'),
('Parroquia', 209, 'Cecilio Acosta'),
('Parroquia', 209, 'Los Teques'),
('Parroquia', 209, 'El Jarillo'),
('Parroquia', 209, 'San Pedro'),
('Parroquia', 209, 'Tácata'),
('Parroquia', 209, 'Paracotos'),
('Parroquia', 210, 'Cartanal'),
('Parroquia', 210, 'Santa Teresa del Tuy'),
('Parroquia', 211, 'La Democracia'),
('Parroquia', 211, 'Ocumare del Tuy'),
('Parroquia', 211, 'Santa Bárbara'),
('Parroquia', 212, 'San Antonio de los Altos'),
('Parroquia', 213, 'Río Chico'),
('Parroquia', 213, 'El Guapo'),
('Parroquia', 213, 'Tacarigua de la Laguna'),
('Parroquia', 213, 'Paparo'),
('Parroquia', 213, 'San Fernando del Guapo'),
('Parroquia', 214, 'Santa Lucía del Tuy'),
('Parroquia', 215, 'Cúpira'),
('Parroquia', 215, 'Machurucuto'),
('Parroquia', 216, 'Guarenas'),
('Parroquia', 217, 'San Antonio de Yare'),
('Parroquia', 217, 'San Francisco de Yare'),
('Parroquia', 218, 'Leoncio Martínez'),
('Parroquia', 218, 'Petare'),
('Parroquia', 218, 'Caucagüita'),
('Parroquia', 218, 'Filas de Mariche'),
('Parroquia', 218, 'La Dolorita'),
('Parroquia', 219, 'Cúa'),
('Parroquia', 219, 'Nueva Cúa'),
('Parroquia', 220, 'Guatire'),
('Parroquia', 220, 'Bolívar'),
('Parroquia', 221, 'San Antonio de Maturín'),
('Parroquia', 221, 'San Francisco de Maturín'),
('Parroquia', 222, 'Aguasay'),
('Parroquia', 223, 'Caripito'),
('Parroquia', 224, 'El Guácharo'),
('Parroquia', 224, 'La Guanota'),
('Parroquia', 224, 'Sabana de Piedra'),
('Parroquia', 224, 'San Agustín'),
('Parroquia', 224, 'Teresen'),
('Parroquia', 224, 'Caripe'),
('Parroquia', 225, 'Areo'),
('Parroquia', 225, 'Capital Cedeño'),
('Parroquia', 225, 'San Félix de Cantalicio'),
('Parroquia', 225, 'Viento Fresco'),
('Parroquia', 226, 'El Tejero'),
('Parroquia', 226, 'Punta de Mata'),
('Parroquia', 227, 'Chaguaramas'),
('Parroquia', 227, 'Las Alhuacas'),
('Parroquia', 227, 'Tabasca'),
('Parroquia', 227, 'Temblador'),
('Parroquia', 228, 'Alto de los Godos'),
('Parroquia', 228, 'Boquerón'),
('Parroquia', 228, 'Las Cocuizas'),
('Parroquia', 228, 'La Cruz'),
('Parroquia', 228, 'San Simón'),
('Parroquia', 228, 'El Corozo'),
('Parroquia', 228, 'El Furrial'),
('Parroquia', 228, 'Jusepín'),
('Parroquia', 228, 'La Pica'),
('Parroquia', 228, 'San Vicente'),
('Parroquia', 229, 'Aparicio'),
('Parroquia', 229, 'Aragua de Maturín'),
('Parroquia', 229, 'Chaguamal'),
('Parroquia', 229, 'El Pinto'),
('Parroquia', 229, 'Guanaguana'),
('Parroquia', 229, 'La Toscana'),
('Parroquia', 229, 'Taguaya'),
('Parroquia', 230, 'Cachipo'),
('Parroquia', 230, 'Quiriquire'),
('Parroquia', 231, 'Santa Bárbara'),
('Parroquia', 232, 'Barrancas'),
('Parroquia', 232, 'Los Barrancos de Fajardo'),
('Parroquia', 233, 'Uracoa'),
('Parroquia', 234, 'Antolín del Campo'),
('Parroquia', 235, 'Arismendi'),
('Parroquia', 236, 'García'),
('Parroquia', 236, 'Francisco Fajardo'),
('Parroquia', 237, 'Bolívar'),
('Parroquia', 237, 'Guevara'),
('Parroquia', 237, 'Matasiete'),
('Parroquia', 237, 'Santa Ana'),
('Parroquia', 237, 'Sucre'),
('Parroquia', 238, 'Aguirre'),
('Parroquia', 238, 'Maneiro'),
('Parroquia', 239, 'Adrián'),
('Parroquia', 239, 'Juan Griego'),
('Parroquia', 239, 'Yaguaraparo'),
('Parroquia', 240, 'Porlamar'),
('Parroquia', 241, 'San Francisco de Macanao'),
('Parroquia', 241, 'Boca de Río'),
('Parroquia', 242, 'Tubores'),
('Parroquia', 242, 'Los Baleales'),
('Parroquia', 243, 'Vicente Fuentes'),
('Parroquia', 243, 'Villalba'),
('Parroquia', 244, 'San Juan Bautista'),
('Parroquia', 244, 'Zabala'),
('Parroquia', 245, 'Agua Blanca'),
('Parroquia', 246, 'Capital Araure'),
('Parroquia', 246, 'Río Acarigua'),
('Parroquia', 247, 'Capital Esteller'),
('Parroquia', 247, 'Uveral'),
('Parroquia', 248, 'Guanare'),
('Parroquia', 248, 'Córdoba'),
('Parroquia', 248, 'San José de la Montaña'),
('Parroquia', 248, 'San Juan de Guanaguanare'),
('Parroquia', 248, 'Virgen de la Coromoto'),
('Parroquia', 249, 'Guanarito'),
('Parroquia', 249, 'Trinidad de la Capilla'),
('Parroquia', 249, 'Divina Pastora'),
('Parroquia', 250, 'Monseñor José Vicente de Unda'),
('Parroquia', 250, 'Peña Blanca')